name: Keep SQL Only

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove non-SQL files
        run: |
          find . -type f \
          ! -name "*.sql" \
          ! -name ".gitignore" \
          ! -path "./.git/*" \
          ! -path "./.github/*" \
          -delete

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "Keep only SQL files"
            git push
          fi
